import code as c 
c.create("sastra",25)
c.create("src",70,3600) 
c.read("sastra")
c.read("src")
c.create("sastra",50)
c.modify("sastra",55)
c.delete("sastra")
t1=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
t1.start()
t1.sleep()
t2=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
t2.start()
t2.sleep()
